---
title: "EC3371"
author: "Leanne"
date: "13 March 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dataframe, include=FALSE}

 #Data Cleaning 
 library(dplyr)
 library(stringr)

 df <- read.csv("WDI_Data.csv")
 df.2013 <- dplyr::select(df, 
                          Country.Name,
                          Country.Code,
                          Indicator.Name,
                          Indicator.Code,
                          X2012,
                          X2013)
 
 df.2013$Indicator.Name <- as.character(as.factor(df.2013$Indicator.Name))
 df.2013$Country.Name <- as.character(as.factor(df.2013$Country.Name))
 df.2013$Country.Code <- as.character(as.factor(df.2013$Country.Code))
 df.2013$Indicator.Code <- as.character(as.factor(df.2013$Indicator.Code))
 
 df.12 <- dplyr::select(df.2013, 
                        Country.Name,
                        Country.Code,
                        Indicator.Name,
                        Indicator.Code,
                        X2012)
 
 df.12 <- df.12[complete.cases(df.12),]
 
 
 df.13 <- dplyr::select(df.2013, 
                        Country.Name,
                        Country.Code,
                        Indicator.Name,
                        Indicator.Code,
                        X2013)
 df.13 <- df.13[complete.cases(df.13),]
 
 #GDP Data 
 gdp <- "GDP"
 df.gdp.13 <- df.13
 df.gdp.13$GDP <- str_detect(df.gdp.13$Indicator.Name, gdp)
 df.gdp.13 <- df.gdp.13[df.gdp.13$GDP == "TRUE",]
 
 #Isolating a particular GDP, GDP per cap for constant 2010$
 df.gdp.13 <- df.gdp.13[df.gdp.13$Indicator.Code == "NY.GDP.PCAP.KD",]
 
 df.gdp.12 <- df.12
 df.gdp.12 <- df.gdp.12[df.gdp.12$Indicator.Code == "NY.GDP.PCAP.KD",]
 
 df.gdp.12.13 <- merge.data.frame(df.gdp.12, df.gdp.13, by = "Country.Name")
 df.gdp.12.13 <- dplyr::select(df.gdp.12.13,
                               Country.Name,
                               Country.Code.x,
                               X2013,
                               X2012)
 df.gdp.12.13 <- dplyr::rename(df.gdp.12.13,
                               Country.Code = Country.Code.x,
                               GDP.2012 = X2012 ,
                               GDP.2013 = X2013)
 
 #Air Pollution Data 
 library(stringr)
 air <- "PM2.5"
 df.air <- df.13
 df.air$Air.Pollution <- str_detect(df.air$Indicator.Name, air)
 df.air <- df.air[df.air$Air.Pollution == "TRUE",]
 df.air <- df.air[, -c(6)]
 df.air.avg.pol <- df.air[df.air$Indicator.Code == "EN.ATM.PM25.MC.M3",]
 df.air.avg.pol <- dplyr::select(df.air.avg.pol,
                                 Country.Name,
                                 X2013)
 colnames(df.air.avg.pol)[2] <- "Mean.Annual.Exposure.PM2.5.2013"
 df.gdp.air <- merge.data.frame(df.gdp.12.13, df.air.avg.pol, by = "Country.Name")
 df.gdp.air$Log.GDP.2013 <- log(df.gdp.air$GDP.2013)
 df.gdp.air$Log.GDP.2012 <- log(df.gdp.air$GDP.2012)
 df.gdp.air$Change.Log.GDP <- (df.gdp.air$Log.GDP.2013 - df.gdp.air$Log.GDP.2012)
 df.gdp.air$Growth.Log.GDP <- df.gdp.air$Change.Log.GDP/df.gdp.air$Log.GDP.2012
 library(ggplot2)
 library(ggthemes)

```


```{r gdp pollution plot, echo=FALSE, fig.width=7.29, fig.height=4.5}

ggplot(df.gdp.air, aes(x=Mean.Annual.Exposure.PM2.5.2013, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, 
                method.args = list(family = "symmetric"), 
                aes(color ="LOESS") ) + 
        geom_smooth(method = "lm", 
                    formula = y ~ poly(x, 2, raw = TRUE), 
                    aes(color = "Quadratic")) +
      scale_colour_manual(name = "Curve Type",values=c("blue","green")) +
      ggtitle("Relationship between Log GDP and Air Pollution in 2013") + 
      xlab("\nPM 2.5 Mean Annual Exposure") + 
      ylab("Log GDP per capita (constant 2010 US$)\n")  +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))

ggsave("Qn1-1.png")

 loggdp.air.reg <- lm(Log.GDP.2013~Mean.Annual.Exposure.PM2.5.2013+I(Mean.Annual.Exposure.PM2.5.2013^2), data = df.gdp.air)
 
 loggdp.air.reg.lm <- lm(Log.GDP.2013~Mean.Annual.Exposure.PM2.5.2013, data = df.gdp.air)
 
 pander::pander(loggdp.air.reg.lm)
 
 pander::pander(loggdp.air.reg)

 
 df.gdp.air75 <- df.gdp.air[df.gdp.air$Mean.Annual.Exposure.PM2.5.2013 <= 75,]
 ggplot(df.gdp.air75, aes(x=Mean.Annual.Exposure.PM2.5.2013, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, method.args = list(family = "symmetric")) + 
        geom_smooth(method = "lm", formula = y ~ poly(x, 2), 
color = "green") +
      ggtitle("Relationship between Log GDP and Air Pollution in 2013") + 
      xlab("\nPM 2.5 Mean Annual Exposure") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))
 
  df.gdp.air50 <- df.gdp.air[df.gdp.air$Mean.Annual.Exposure.PM2.5.2013 <= 50,]
 ggplot(df.gdp.air50, aes(x=Mean.Annual.Exposure.PM2.5.2013, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, method.args = list(family = "symmetric")) + 
        geom_smooth(method = "lm", formula = y ~ poly(x, 2), 
color = "green") +
      ggtitle("Relationship between Log GDP and Air Pollution in 2013") + 
      xlab("\nPM 2.5 Mean Annual Exposure") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))

```

```{r change gdp pollution plot, echo=FALSE, fig.width=7.29, fig.height=4.5}

ggplot(df.gdp.air, aes(x=Mean.Annual.Exposure.PM2.5.2013, y= Change.Log.GDP)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, method.args = list(family = "symmetric")) + 
      ggtitle("Relationship between Growth Log GDP and Air Pollution in 2013") + 
      xlab("\nPM 2.5 Mean Annual Exposure") + 
      ylab("Growth in Log GDP per capita (constant 2010 US$)\n") + 
      labs (caption = "Formula for Growth = (Log GDP per capita in 2013 - Log GDP per capita in 2012)" ) +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5))

ggsave("Qn1b.png")

change.gdp.air.reg <- lm(Change.Log.GDP~Mean.Annual.Exposure.PM2.5.2013+I(Mean.Annual.Exposure.PM2.5.2013^2), data = df.gdp.air)
 pander::pander(change.gdp.air.reg)

#Since there's an annoying point, drop it from sample

 ggplot(df.gdp.air, aes(x=Mean.Annual.Exposure.PM2.5.2013, y= Change.Log.GDP)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, method.args = list(family = "symmetric")) + 
      ggtitle("Relationship between Growth Log GDP and Air Pollution in 2013") + 
      xlab("\nPM 2.5 Mean Annual Exposure") + 
        ylim(-0.1,0.2) +
      ylab("Growth in Log GDP per capita (constant 2010 US$)\n") + 
      labs (caption = "Outlier (Growth < -0.4) was removed for aesthetic purposes. \n Formula for Growth = Log GDP per capita in 2013 - Log GDP per capita in 2012\n") +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"),
            plot.caption = element_text(face = "italic"))

ggsave("Qn1c.png")

 gdp.air.reg <- lm(Change.Log.GDP~Mean.Annual.Exposure.PM2.5.2013, data = df.gdp.air)
 pander::pander(gdp.air.reg)

```

```{r population density, include=FALSE}

 df.popdensity.13 <- df.13[df.13$Indicator.Code == "EN.POP.DNST", ]
 df.popdensity.13 <- dplyr::select(df.popdensity.13, 1,5)
 colnames(df.popdensity.13)[2] <- "Population.density"
 df.gdp.air.popdens <- merge.data.frame(df.gdp.air, df.popdensity.13, by = "Country.Name")

```

```{r age dependncy ration, include=FALSE}

 df.adr.13 <- df.13[df.13$Indicator.Code=="SP.POP.DPND",]
 df.adr.13 <- dplyr::select(df.adr.13, 1 , 5)
 colnames(df.adr.13)[2] <- "Age.Dependency.Ratio"
 df.gdp.air.manu.adr <- merge.data.frame(df.gdp.air, df.adr.13, by = "Country.Name")
 
 
 df.oadr.13 <- df.13[df.13$Indicator.Code=="SP.POP.DPND.OL",]
 df.oadr.13 <- dplyr::select(df.oadr.13, 1 , 5)
 colnames(df.oadr.13)[2] <- "Old.Age.Dependency.Ratio"
 df.gdp.air.manu.adr.oadr <- merge.data.frame(df.gdp.air.manu.adr, df.oadr.13, by = "Country.Name")
 


```

```{r adr plot, echo=FALSE, fig.width=7.29, fig.height=4.5}

 ggplot(df.gdp.air.manu.adr, aes(x=Age.Dependency.Ratio, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
   geom_smooth(method = loess, 
                method.args = list(family = "symmetric"), 
                aes(color ="LOESS") ) + 
        geom_smooth(method = "lm", 
                    aes(color = "Linear")) +
      scale_colour_manual(name = "Curve Type",values=c("green","blue")) +
      ggtitle("Relationship between Log GDP and Age Dependency Ratio in 2013") + 
      xlab("\n Age dependency ratio (% of working-age population)") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"),
            plot.caption = element_text(face = "italic"))

ggsave("Qn2.png")

 adr.reg <- lm(Log.GDP.2013~Age.Dependency.Ratio, data = df.gdp.air.manu.adr)
 adr.reg.2 <- lm(Log.GDP.2013~Age.Dependency.Ratio+I(Age.Dependency.Ratio^2), data = df.gdp.air.manu.adr.oadr)
 
 library(memisc)
 memisc::mtable(adr.reg)
 pander::pander(adr.reg)
 pander::pander(adr.reg.2)


 ggplot(df.gdp.air.manu.adr.oadr, aes(x=Old.Age.Dependency.Ratio, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, method.args = list(family = "symmetric")) + 
      ggtitle("Relationship between Log GDP and Old Age Dependency Ratio in 2013") + 
      xlab("\n Age dependency ratio, old (% of working-age population)") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"),
            plot.caption = element_text(face = "italic"))

ggsave("Qn2a.png")


 ggplot(df.gdp.air.manu.adr, aes(x=Age.Dependency.Ratio, y= Change.Log.GDP)) +
    geom_point(shape=19) +   
   geom_smooth(method = loess, 
                method.args = list(family = "symmetric"), 
                aes(color ="LOESS") ) + 
        geom_smooth(method = "lm", 
                    aes(color = "Linear")) +
          ylim(-0.1,0.2) +
      scale_colour_manual(name = "Curve Type",values=c("green","blue")) +
      ggtitle("\nRelationship between Growth Log GDP and Age Dependency Ratio in 2013") + 
      xlab("\n Age dependency ratio (% of working-age population)") + 
      ylab("Growth Log GDP per capita \n (constant 2010 US$)\n") + 
      labs (caption = "Outlier (Growth < -0.4) was removed for asthetic purposes.\n 
            Growth = Log GDP per capita in 2013 - Log GDP per capita in 2012 \n") +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"),
            plot.caption = element_text(face = "italic"))
 ggsave("Qn2ag.png")
 
 change.gdp.age.reg <- lm(Change.Log.GDP~Age.Dependency.Ratio, data = df.gdp.air.manu.adr)
 summary.lm(change.gdp.age.reg)
 pander::pander(change.gdp.age.reg)
 

```



```{r change gdp pop density plot, echo=FALSE, fig.width=7.29, fig.height=4.5}

ggplot(df.gdp.air.popdens, aes(x=Population.density, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method=lm) 

ggsave("Qn2a.png")

```


```{r infant mort, echo =FALSE}

 #SP.DYN.IMRT.IN
  df.im.13 <- df.13[df.13$Indicator.Code=="SP.DYN.IMRT.IN",]
 df.im.13 <- dplyr::select(df.im.13, 1 , 5)
 colnames(df.im.13)[2] <- "Infant.Mortality"
 df.gdp.air.manu.adr.im <- merge.data.frame(df.gdp.air.manu.adr, df.im.13, by = "Country.Name")

```

```{r infant graph, echo=FALSE, fig.width=7.29, fig.height=4.5}

ggplot(df.gdp.air.manu.adr.im, aes(x=Infant.Mortality, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, 
                method.args = list(family = "symmetric"), 
                aes(color ="LOESS") ) + 
        geom_smooth(method = "lm", 
                    formula = y ~ poly(x, 2, raw = TRUE), 
                    aes(color = "Quadratic")) +
      scale_colour_manual(name = "Curve Type",values=c("blue","green")) +
      ggtitle("Relationship between Infant Mortality & Log GDP per Capita") + 
      xlab("\n Mortality rate, infant (per 1,000 live births)") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))

ggsave("Qn2im.png")

 gdp.im.qrad.reg <- lm(Log.GDP.2013~Infant.Mortality+I(Infant.Mortality^2), data = df.gdp.air.manu.adr.im)
 pander::pander(gdp.im.qrad.reg)
 
 
 ggplot(df.gdp.air.manu.adr.im, aes(x=Infant.Mortality, y= Change.Log.GDP)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, 
                method.args = list(family = "symmetric"), 
                aes(color ="LOESS") ) + 
        geom_smooth(method = "lm", 
                    aes(color = "Linear")) +
        scale_colour_manual(name = "Curve Type",values=c("green","blue")) +
       ylim(-0.1,0.2) +
        labs (caption = "Outlier (Growth < -0.4) was removed for asthetic purposes.\n 
            Growth = Log GDP per capita in 2013 - Log GDP per capita in 2012 \n") +
      ggtitle("Relationship between Infant Morality & Growth Log GDP per Capita") + 
      xlab("\n Mortality rate, infant (per 1,000 live births)") + 
      ylab("Growth Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))
 
 summary.lm(lm(Change.Log.GDP~Infant.Mortality, data = df.gdp.air.manu.adr.im))

ggsave("Qn2im-g.png")

```
```{r pop growth, echo =FALSE}

#SP.POP.GROW
 df.popg.13 <- df.13[df.13$Indicator.Code=="SP.POP.GROW",]
 df.popg.13 <- dplyr::select(df.popg.13, 1 , 5)
 colnames(df.popg.13)[2] <- "Pop.Growth"
 df.gdp.air.manu.adr.popg <- merge.data.frame(df.gdp.air.manu.adr, df.popg.13, by = "Country.Name")


```

```{r popg graph, echo=FALSE, fig.width=7.29, fig.height=4.5}

ggplot(df.gdp.air.manu.adr.popg, aes(x=Pop.Growth, y= Log.GDP.2013, label=Country.Code)) +
    geom_point(shape=19) + 
       geom_text(size=3, hjust = 2) +
     geom_smooth(method = loess, 
                method.args = list(family = "symmetric"), 
                aes(color ="LOESS") ) + 
        geom_smooth(method = "lm", 
                    formula = y ~ poly(x, 3, raw = TRUE), 
                    aes(color = "Cubic")) +
      scale_colour_manual(name = "Curve Type",values=c("green","blue")) +
      ggtitle("Relationship between Population Growth & Log GDP per Capita") + 
      xlab("\n Population growth (annual %)") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))

ggsave("Qn2popg.png")

 summary.lm(lm(Log.GDP.2013~Pop.Growth, data = df.gdp.air.manu.adr.popg))
  summary.lm(lm(Log.GDP.2013~Pop.Growth+I(Pop.Growth^2), data = df.gdp.air.manu.adr.popg))
 gdp.popg.qrad.reg <- lm(Log.GDP.2013~Pop.Growth+I(Pop.Growth^2)+I(Pop.Growth^3), data = df.gdp.air.manu.adr.popg)
 pander::pander(gdp.popg.qrad.reg)
 
  summary.lm(gdp.popg.qrad.reg)
  
  ggplot(df.gdp.air.manu.adr.popg, aes(x=Pop.Growth, y= Change.Log.GDP)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, 
                method.args = list(family = "symmetric"), 
                aes(color ="LOESS") ) + 
        geom_smooth(method = "lm", 
                    formula = y ~ poly(x, 2, raw = TRUE), 
                    aes(color = "Quadratic")) +
      scale_colour_manual(name = "Curve Type",values=c("blue","green")) +
         ylim(-0.1,0.2) +
        labs (caption = "Outlier (Growth < -0.4) was removed for asthetic purposes.\n 
            Growth = Log GDP per capita in 2013 - Log GDP per capita in 2012 \n") +
      ggtitle("Relationship between Population Growth & Growth Log GDP per Capita") + 
      xlab("\n Population growth (annual %)") + 
      ylab("Growth Log GDP per capita \n
           (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))
  ggsave("Qn2popgc.png")
  summary.lm(lm(Change.Log.GDP~Pop.Growth, data = df.gdp.air.manu.adr.popg))
  change.log.popg.reg <- lm(Change.Log.GDP~Pop.Growth+I(Pop.Growth^2)+I(Pop.Growth^3), data = df.gdp.air.manu.adr.popg)
  change.log.popg.reg1 <- lm(Change.Log.GDP~Pop.Growth+I(Pop.Growth^2), 
                             data = df.gdp.air.manu.adr.popg)
  summary.lm(change.log.popg.reg1)
  
  pander::pander(change.log.popg.reg1)


```


```{r Death Rates, echo=FALSE}

#Death Rates SP.DYN.CDRT.IN

 df.death.13 <- df.13[df.13$Indicator.Code=="SP.DYN.CDRT.IN",]
 df.death.13 <- dplyr::select(df.death.13, 1 , 5)
 colnames(df.death.13)[2] <- "Crude.Death.Rates"
 df.gdp.air.manu.adr.death <- merge.data.frame(df.gdp.air.manu.adr, df.death.13, by = "Country.Name")


```

```{r death graph, echo =FALSE, fig.width=7.29, fig.height=4.5}

ggplot(df.gdp.air.manu.adr.death, aes(x=Crude.Death.Rates, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, method.args = list(family = "symmetric")) + 
      ggtitle("Relationship between Death Rates & Log GDP per Capita") + 
       geom_smooth(method = "lm", formula = y ~ poly(x, 3, raw = TRUE), color = "green") + 
      xlab("\n Death rate, crude (per 1,000 people)") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))

ggsave("Qn2d.png")

 gdp.death.qrad.reg <- lm(Log.GDP.2013~Crude.Death.Rates+I(Crude.Death.Rates^2), data = df.gdp.air.manu.adr.death)
 pander::pander(gdp.death.qrad.reg)


 

```

```{r manufacturing, echo=FALSE}

 manufacturing <- "Manufacturing"
 df.manufacturing <- df.13
 df.manufacturing$Manufacture <- str_detect(
       df.manufacturing$Indicator.Name, manufacturing)
 df.manufacturing <- df.manufacturing[df.manufacturing$Manufacture == "TRUE",]
 df.manufacturing <- df.manufacturing[df.manufacturing$Indicator.Code == "NV.IND.MANF.ZS",]
 df.manufacturing <- dplyr::select(df.manufacturing,
                                   Country.Name,
                                   X2013)
 colnames(df.manufacturing)[2] <- "Percent.Manufacture.GDP"
 df.gdp.air.manu <- merge.data.frame(df.gdp.air, df.manufacturing, by = "Country.Name")
 


```

```{r manu graph, echo =FALSE, fig.width=7.29, fig.height=4.5}

ggplot(df.gdp.air.manu, aes(x=Percent.Manufacture.GDP, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method = loess, method.args = list(family = "symmetric")) + 
      ggtitle("Relationship between Share of Manufacturing & Log GDP per Capita") + 
      xlab("\n Manufacturing, value added (% of GDP)") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))

ggsave("Qn3.png")

 gdp.manu.reg <- lm(Log.GDP.2013 ~ Percent.Manufacture.GDP, data = df.gdp.air.manu)
 pander::pander(gdp.manu.reg)
 
 ggplot(df.gdp.air.manu, aes(x=Percent.Manufacture.GDP, y= Log.GDP.2013)) +
    geom_point(shape=19) +   
    geom_smooth(method = lm, colour = "green") + 
      ggtitle("Relationship between Share of Manufacturing & Log GDP per Capita") + 
      xlab("\n Manufacturing, value added (% of GDP)") + 
      ylab("Log GDP per capita (constant 2010 US$)\n") + 
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))

 ggsave("Qn3lm.png")
 
 gdp.manu.qrad.reg <- lm(Log.GDP.2013~Percent.Manufacture.GDP+I(Percent.Manufacture.GDP^2), data = df.gdp.air.manu)
 pander::pander(gdp.manu.qrad.reg)
```

```{r dataset tariff, echo=FALSE}

 dftariff <- read.csv("Applied_MFN_Tariffs.txt", sep = "", header = TRUE)
 dftariff$Description <- as.character(as.factor(dftariff$Description))
 dftariff$Type <- ifelse(dftariff$HS.code.level ==2, dftariff$Description, NA)
 dftariff$firsttwo <- substr(dftariff$Product, start = 1, stop = 2)
 dftariff$Reporter <- as.character(as.factor(dftariff$Reporter))
 
 library(zoo)
 tariff <- dftariff %>% 
       group_by(firsttwo, Reporter) %>% 
       na.locf(19) %>% ungroup

 tariff <- tariff[tariff$HS.code.level == 6, ]
 tariff$AVDuty.average <- as.numeric(tariff$AVDuty.average) 
 tariff$AVDuty.minimum <- as.numeric(tariff$AVDuty.minimum) 
 tariff$AVDuty.maximum <- as.numeric(tariff$AVDuty.maximum)
 tariff <- tariff[,colSums(is.na(tariff))<nrow(tariff)]
 
 library(stringr)
 tariff$Reporter <- str_replace_all(tariff$Reporter, "[[:punct:]]", "")
 
 #Identify Malayisia's Tariff since Singapore has no tariffs
 tariff0 <- tariff[tariff$Reporter =="Malaysia",]
 tariff0 <- na.omit(tariff0)
 tariff0$first <- substr(tariff0$Product, start = 1, stop = 1)
 tariff0$Product.Num <- as.numeric(tariff0$Product)
 
 
 #Identify Products with Tariffs more than 35%
 tariff35 <- tariff[tariff$AVDuty.minimum >= 35, ]
 tariff35 <- tariff35[apply(tariff35, 1, function(y) !all(is.na(y))),]
 tariff35 <- dplyr::select(tariff35, 1, 5, 9, 18, 19)
 
 library(pander)
 panderOptions('table.split.table', Inf)
 
 summary <- tariff %>% 
		group_by(Type, Reporter) %>% 
		summarise( Total.Average.Tariff.Rates = sum(AVDuty.average),
			   Total.Min.Tariff.Rates = sum(AVDuty.minimum),
			   Total.Max.Tariff.Rates = sum(AVDuty.maximum) )
 
 tariff$Type <- as.factor(tariff$Type)
 tarifftype <- pander(dplyr::count(tariff,Reporter))

```

```{r tariff > 35 , echo=FALSE}

 pander(tariff35)

```

It is possible that the Tariffs are high for such products to discourage foreign countries from buying them. Grains may be due to food security. 

```{r distribution of tarriff, echo=FALSE}

library(ggplot2)
tariff0.0 <- tariff0[tariff0$first == '0',] 
tariff0.1 <- tariff0[tariff0$first == '1',] 
tariff0.2 <- tariff0[tariff0$first == '2',] 
tariff0.3 <- tariff0[tariff0$first == '3',] 
tariff0.4 <- tariff0[tariff0$first == '4',] 
tariff0.5 <- tariff0[tariff0$first == '5',] 
tariff0.6 <- tariff0[tariff0$first == '6',] 
tariff0.7 <- tariff0[tariff0$first == '7',] 
tariff0.8 <- tariff0[tariff0$first == '8',] 
tariff0.9 <- tariff0[tariff0$first == '9',] 

dis.tariff.0 <- ggplot(tariff0, aes(x = Product.Num, y = AVDuty.average)) +
      geom_point(aes(colour=as.numeric(firsttwo))) + 
      scale_color_gradient(low="blue", high="red")+ 
      theme_minimal() +  
      theme(plot.title = element_text(hjust = 0.5, face = "bold")) +
      labs(title = "Distribution of Tariff in Malaysia",
           x = "\nProduct Code",
           y = "Average Tariff (%)\n",
           colour = "Product Type",
           caption = "Product Type derived from first 2 digits of the Product Code\n"
           )


dis.tariff.0
 ggsave("tariff.png")


#Mean of Malaysia Tariff
summary <- tariff %>%  na.omit() %>% group_by(Reporter) %>%
  summarise(`25%`=quantile(AVDuty.average, probs=0.25),
            `50%`=quantile(AVDuty.average, probs=0.5),
            `75%`=quantile(AVDuty.average, probs=0.75),
            avg=mean(AVDuty.average),
            n=n())


```

```{r}
pander::pander(summary)
```

```{r plotly, eval=FALSE, include=FALSE}

library(plotly)
# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)

g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'Mercator')
)

p <- plot_geo(df.gdp.air) %>%
  add_trace(
    z = ~Mean.Annual.Exposure.PM2.5.2013, color = ~Mean.Annual.Exposure.PM2.5.2013, colors = 'Blues',
    text = ~Country.Name, locations = ~Country.Code, marker = list(line = l)
  ) %>%
  colorbar(title = 'Mean Annual Exposure PM 2.5') %>%
  layout(
    title = 'Mean Annual Exposure PM 2.5.in 2013',
    geo = g
  ) 

Sys.setenv("plotly_username"="leannetanjy")
Sys.setenv("plotly_api_key"="2BhVxnhqDRTTuEDO7Xee")

chart_link = plotly_POST(p, filename="MeanAnnualPollution")
chart_link
p

```
```{r, eval=FALSE, include=FALSE}
library(plotly)
# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)

g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'Mercator')
)

q <- plot_geo(df.gdp.air) %>%
  add_trace(
    z = ~GDP.2013, color = ~GDP.2013, colors = 'Purples',
    text = ~Country.Name, locations = ~Country.Code, marker = list(line = l)
  ) %>%
  colorbar(title = 'GDP 2013') %>%
  layout(
    title = 'GDP constant 2010$ in 2013',
    geo = g
  ) 

Sys.setenv("plotly_username"="leannetanjy")
Sys.setenv("plotly_api_key"="2BhVxnhqDRTTuEDO7Xee")

chart_link = plotly_POST(q, filename="GDP in 2013")
chart_link
q

```
```

  
